version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: redisapidatabase
    environment:
      MSSQL_SA_PASSWORD: Rahul@123456789
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - redisnetwork
    volumes:
      - redis-volumn:/var/opt/mssql
        
    
  api:
    image: redis-docker-api
    container_name: redis-api
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=redisapidatabase,1433;Database=InMemoryDatabase;User Id=sa;Password=Rahul@123456789;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - redisnetwork
    restart: always
    
networks:
  redisnetwork:

volumes:
  redis-volumn:
